import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { useEffect, useState } from "react";
import { getArticles } from "../../components/api/articles";
import ArticleCard from "../../components/articles/articleItem";

import Footer from "../../components/footer";
import ArticleLoadingCard from "../../components/loading/articles";


import Navbar from "../../components/navbar";

const Home: NextPage = () => {
  const [articles, setArticles] = useState<any[]>([])
  const [isLoading, seIsLoading] = useState<boolean>(true)
  useEffect(() => {
    getArticlesList();
  },[ ])
  useEffect(() => {
  console.log(articles)
  },[articles])

  const getArticlesList = async () => {
    try {
      const data =await getArticles()
        setArticles(data)
        seIsLoading(false)
    } catch (error) {
        console.log(error)
        seIsLoading(false)
    }
  }
  return (
    <div >
      <Head>
        <title>قضية-مقلات</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="57x57"
          href="/favicons/apple-icon-57x57.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="60x60"
          href="/favicons/apple-icon-60x60.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="72x72"
          href="/favicons/apple-icon-72x72.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="76x76"
          href="/favicons/apple-icon-76x76.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="114x114"
          href="/favicons/apple-icon-114x114.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="120x120"
          href="/favicons/apple-icon-120x120.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="144x144"
          href="/favicons/apple-icon-144x144.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="152x152"
          href="/favicons/apple-icon-152x152.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicons/apple-icon-180x180.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="192x192"
          href="/favicons/android-icon-192x192.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicons/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="96x96"
          href="/favicons/favicon-96x96.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicons/favicon-16x16.png"
        />
        <link rel="manifest" href="/favicons/manifest.json" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="msapplication-TileImage" content="/ms-icon-144x144.png" />
        <meta name="theme-color" content="#ffffff" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main dir="rtl" className="min-h-[90vh]">
        <Navbar />
        <div className="pt-20 px-7 md:px-[10%]">
          <h1 className="text-2xl font-semibold text-main-900 py-10">مقلات </h1>
          <div className="grid lg:grid-cols-1 grid-cols-1 gap-4">
            {isLoading &&
                  <ArticleLoadingCard />
            }
            {!isLoading && articles.length == 0 &&
              <>
              <div className="text-center mx-auto">
              <Image src="/assets/logo.png" width="100" height="100" />
                  <h1 className="font-bold text-2xl">لم يتم العثور على مقالات</h1>
              </div>
              </>
            }
          {articles.map((post:any) => {
            return <ArticleCard
              key={post.id}
            href={`/articles_prisoners/show?id=${post.id}`}
            title={post.title}
            date={post.created.toDate().toString()}
            />
           
          })

          }

          </div>
        </div>
   
      </main>

      <Footer />
    </div>
  );
};

export default Home;
