import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { getMale } from "../../components/api/male";
import Footer from "../../components/footer";
import News from "../../components/home/news";
import Recent from "../../components/home/recent";
import Navbar from "../../components/navbar";
import PrisonersCard from "../../components/prisoners/prisonersCard";
import TitleWithAction from "../../components/titleWithAction";


const Home: NextPage = () => {
  const [male, setMale] = useState<any[]>([])
  useEffect(() => {
    getMaleList();
  },[
    
  ])

  const getMaleList = async () => {
    try {
      const data =await getMale()
      setMale(data)
    } catch (error) {
      console.log(error)
    }
  }
  return (
    <div >
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="57x57"
          href="/favicons/apple-icon-57x57.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="60x60"
          href="/favicons/apple-icon-60x60.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="72x72"
          href="/favicons/apple-icon-72x72.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="76x76"
          href="/favicons/apple-icon-76x76.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="114x114"
          href="/favicons/apple-icon-114x114.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="120x120"
          href="/favicons/apple-icon-120x120.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="144x144"
          href="/favicons/apple-icon-144x144.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="152x152"
          href="/favicons/apple-icon-152x152.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicons/apple-icon-180x180.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="192x192"
          href="/favicons/android-icon-192x192.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicons/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="96x96"
          href="/favicons/favicon-96x96.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicons/favicon-16x16.png"
        />
        <link rel="manifest" href="/favicons/manifest.json" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="msapplication-TileImage" content="/ms-icon-144x144.png" />
        <meta name="theme-color" content="#ffffff" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main dir="rtl" className="min-h-[90vh]">
        <Navbar />
        <div className="pt-20 px-7 md:px-[10%]">
          <h1 className="text-2xl font-semibold text-main-900 py-10">الأسرى </h1>
          <div className="grid lg:grid-cols-3 grid-cols-1 gap-4">
          {male.map((post:any) => {
            return <PrisonersCard
              key={post.id}
            href={`/male_prisoners/show?id=${post.id}`}
            img={post.img}
            name={post.name}
            arrestDate={post.arrestDate}
            dateOfBirth={post.dateOfBirth}
            judgment={post.judgment}
            city={post.city}
            title={post.title}
            description={post.description}
            />
           
          })

          }

          </div>
        </div>
   
      </main>

      <Footer />
    </div>
  );
};

export default Home;
